### ISSUE TITLE
使用quansyn中遇到的一些小问题

### ISSUE THREAD

**Issue by wwrwbs** [YuhuYang/QuanSyn#1]
杨博士您好，

非常感谢您开发了这个实用的句法分析工具，整合了大量有用的指标计算和数据分析功能，大大提升了我的科研效率！
不过我在使用您的工具过程中，也出现了一些小的问题，不知道是不是个人操作有误，想和您反馈一下：

1. 我的树库中会出现一些一个词一句话的情况，那么在计算句子层面的mdd等指标时就会出现除以0的错误，具体报错如下：
`Traceback (most recent call last):
  File "/sdb/wangweiran/translation_dep/RM训练集/TransDep_stage2/quansyn/quansyn_quick.py", line 9, in <module>
    analyze(treebanks_path, output_path)
  File "/home/wangweiran/anaconda3/envs/quansyn/lib/python3.10/site-packages/quansyn/depval.py", line 260, in analyze
    sent_data = treebank.calculate_sent_metrics()
  File "/home/wangweiran/anaconda3/envs/quansyn/lib/python3.10/site-packages/quansyn/depval.py", line 125, in calculate_sent_metrics
    sent_data[metric] = metric_functions[metric]()
  File "/home/wangweiran/anaconda3/envs/quansyn/lib/python3.10/site-packages/quansyn/depval.py", line 110, in <lambda>
    'mdd': lambda: [sum(i for i in j if i > 0) / (len(j)-1) for j in dep_data['dd']],
  File "/home/wangweiran/anaconda3/envs/quansyn/lib/python3.10/site-packages/quansyn/depval.py", line 110, in <listcomp>
    'mdd': lambda: [sum(i for i in j if i > 0) / (len(j)-1) for j in dep_data['dd']],
**ZeroDivisionError: division by zero**
`
一个解决方法就是我在前期处理的时候将这些一个词一句话的句子删除，这样就不会报错；另一个解决办法就是在源代码中加入对于除以0情况的处理，例如：
`    try:
        text_metrics = analyzer.calculate_text_metrics(metrics=metrics)
    except ZeroDivisionError as e:
        print(f"ZeroDivisionError in {file_name}: {e}")
        text_metrics = {metric: None for metric in metrics}
`
2. 因为我的树库比较大（一个树库可能有几万个句子），所以目前使用代码来进行分析的时候运算时间比较长，不知道有没有可能后续添加加速计算的选项（比如使用GPU并行计算）
3. 另外您上传的quansyn mini软件的mac版本我这边解压缩之后没有可以直接安装/运行的程序，不知道是不是我个人电脑版本的原因（我的电脑：MacBook Pro M1 Pro芯片，系统版本：macOS: 14.6.1 (23G93)）
<img width="719" alt="SCR-20241117-khep" src="https://github.com/user-attachments/assets/a47487aa-6a0f-44a7-99a4-af2639677d11">

再次感谢您提供如此便捷好用的工具，期待您的回复！

**Comment by YuhuYang** [comment]
您好，感谢您的关注！

1. 独词句只有一个词，只有一个虚拟的依存关系（root），并没有与一个真实的词形成依存关系，所以没有依存距离，会出现除以零的问题。感谢您的意见，我们确实有必要提升对独词句的健壮性测试，我们会在下个版本中更新~
2. 目前测试用的树库规模是20x1000句，全部计算需要约20秒。由于标注树库需要人工校对，我们就没有预设超大规模树库情况。您提的意见很有价值，我们会在今后开发中尝试并行计算。
3. 重新传输了压缩包，启动器位置为dist-quansyn，如果显示打不开，请在隐私与安全中给予权限

再次感谢

**Comment by wwrwbs** [comment]
杨博士您好，

您重新上传的mac版软件已经可以正常运行了，再次感谢！

感谢您的及时回复！

**Comment by YuhuYang** [comment]
您客气了
